config/routes.rb
Rails.application.routes.draw do
  get 'uploads/new'

  get 'uploads/create'

  get 'uploads/index'

  #get 'plants/new' #I'm not sure if this code is actually necessary, since things work as expected without it...

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get    '/plants',  to: 'plants#index'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :plants do
    delete :destroy_picture
  end
  resources :scrap_plants
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  resources :uploads
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<%= favicon_link_tag 'favicon.ico' %>
<link rel="apple-touch-icon" href="https://s3-us-west-2.amazonaws.com/plantbook/img/apple-touch-icon.png"/>
<link rel="apple-touch-icon-precomposed" href="https://s3-us-west-2.amazonaws.com/plantbook/img/apple-touch-icon.png"/>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112947995-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-112947995-1');
</script>

app/views/layouts/_header.html.erb
<!--
-- This file is deprecated in favor of _navbar.html.erb
-->

<header class="navbar navbar-fixed-top" style="padding-left: 16px; padding-right: 16px">
    <%= link_to "Plant Book", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", plants_path %></li>
      </ul>
    </nav>
</header>

app/views/layouts/_navbar.html.erb
<div id="plantbook-nav">
  <div class="plant-nav-left">
    <%= link_to image_tag("nav-logo-30.svg", alt: "Plantbook"), root_path, id: "nav-logo-pic" %>
  </div>
  
  <div class="plant-nav-right">
    <div class="nav-item">
      <%= link_to "Explore", plants_path %>
    </div>
    <div class="nav-item">
      <%= link_to "Users", users_path, id:'users' %>
    </div>
    <% if logged_in? %>
    <ul class="list-inline list-unstyled">
      <li class="dropdown">
        <a class="nav-item nav-item-dropdown" type="button" data-toggle="dropdown"><i class="far fa-ellipsis-h fa-lg"></i></a>
        <ul class="dropdown-menu dropdown-menu-right">
          <li>
            <%= link_to help_path do %>
              <i class="fas fa-question m-r-xs"></i> Help
            <% end %>
          </li>
          <li>
            <%= link_to about_path do %>
              <i class="fas fa-info m-r-xs"></i> About
            <% end %>
          </li>
          <li>
              <a><i class="fal fa-comment-alt m-r-xs"></i> Share feedback</a>
          </li>
          <li>
              <a><i class="fas fa-hashtag m-r-xs"></i> Tweet at us</a>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to logout_path, method: :delete do %>
              <i class="fas fa-sign-out m-r-xs"></i> Log out
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
    <button class="btn btn-outline nav-item">Upgrade</button>
   
    <ul class="list-inline list-unstyled">
      <li class="dropdown nav-item">
        <a class="fa-layers fa-fw nav-item-dropdown nav-bell" style="font-size: 18px" type="button" data-toggle="dropdown">
          <i class="fal fa-bell"></i>
          <span class="fa-layers-counter nav-bell-counter">2</span>
        </a>
        <ul class="dropdown-menu notif-menu dropdown-menu-right">
          <li>
            <div class="notif-header">
              <div>Notifications</div>
              <div><i class="fas fa-cog"></i></div>
            </div>
          </li>
          <li class="divider"></li>
          <li class="notif-area">
              <div class="notif-wrapper">
                <div class="notif-icon"><i class="far fa-cut"></i></div>
                <div class="notif-text unread">
                  Now is a great time to prune your <a class="link">Canby Raspberry</a> plant.
                  <div class="btn-wrapper">
                    <button onclick="location.href = 'https://www.youtube.com/watch?v=ShNGGuO1x4E';" class="btn btn-outline"><i class="far fa-play-circle fa-fw m-r-xs"></i> Learn how</button>
                    <button class="btn btn-outline"><i class="fal fa-dollar-sign fa-fw m-r-xs"></i> Hire someone</button>
                    <button class="btn btn-outline"><i class="fal fa-dollar-sign fa-fw m-r-xs"></i> Buy a pruning kit</button>
                  </div>
                </div>
              </div>
              <div class="notif-wrapper">
                <div class="notif-icon"><i class="fal fa-clock"></i></div>
                <div class="notif-text unread">
                  Based on the weather forecast, next week looks like a great time to feed your <a class="link">Limelight Hydrangaea</a> with a balanced 10/10/10 fertilzer.
                  <div class="btn-wrapper">
                    <button class="btn btn-outline"><i class="fal fa-dollar-sign fa-fw m-r-xs"></i> Buy it now</button>
                  </div>
                </div>
              </div>
              <div class="notif-wrapper">
                <div class="notif-icon"><i class="fal fa-clock"></i></div>
                <div class="notif-text">
                  Based on the weather forecast, next week looks like a great time to feed your <a class="link">Limelight Hydrangaea</a> with a balanced 10/10/10 fertilzer.
                  <div class="btn-wrapper">
                    <button class="btn btn-outline"><i class="fal fa-dollar-sign fa-fw m-r-xs"></i> Buy it now</button>
                  </div>
                </div>
              </div>
          </li>
        </ul>
      </li>
    </ul>

    <div class="nav-item">
      <%= link_to edit_user_path(current_user) do %>
        <i class="fal fa-user-circle m-r-xs" style="font-size: 24px"></i>
      <% end %>
    </div>
    <% else %>
    <div class="nav-item"><span class="border-left"></span></div>
    <div class="nav-item">
      <%= link_to login_path do %>
        Log in
      <% end %>
    </div>
    <div class="nav-item">
      <%= link_to login_path do %>
        <button class="btn btn-primary">Join Free</button>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<!-- MOBILE NAVBAR -->
<div id="plantbook-nav-mobile">
  
  <div>
    <button onclick="openRail()" class="btn-menu-circle-rotate" id="filterToggle">
      <img src="https://s3-us-west-2.amazonaws.com/plantbook/img/filter.svg" alt="Filters" class="nav-icon">
    </button>
  </div>

  <div>
    <img src="https://s3-us-west-2.amazonaws.com/plantbook/img/nav-logo-30.svg" id="nav-logo-mobile">
  </div>

  <div>
    <ul class="list-inline list-unstyled" style="margin-bottom: 0">
      <% if logged_in? %>
        <li class="dropdown">
          <button type="button" class="btn-menu-circle-rotate" data-toggle="dropdown">
            <img src="https://s3-us-west-2.amazonaws.com/plantbook/img/dots.svg" alt="menu" class="nav-icon">
          </button>
          <ul class="dropdown-menu dropdown-menu-right">
            <li>
              <%= link_to help_path do %>
                <i class="fas fa-question m-r-xs"></i> Help
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user) do %>
                <i class="fal fa-user-circle m-r-xs"></i> Account settings
              <% end %>
            </li>
            <li>
              <a data-toggle="modal" data-target="#feedback"><i class="fas fa-envelope-open-o m-r-xs"></i> Comment box</a>

              <!-- Add plant modal -->
              <div class="modal fade" id="feedback" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">Comment box</h4>
                        </div>
                        <div class="modal-body">
                          <input type="area">
                        </div>
                        <div class="modal-footer">
                          <div class="checkbox">
                          </div>
                          <div>
                            <button type="button" class="btn btn-quiet" data-dismiss="modal">Cancel</button>
                          </div>
                        </div>
                    </div>
                </div>
              </div>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <i class="fas fa-sign-out m-r-xs"></i> Log out
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_notification-bar.html.erb
<div id="notification-bar">Share Plantbook! <i class="fa fa-heart fa-lg text-red p-l-xs"></i></div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>

      <% flash.each do |message_type, message| %>
        <% message_type == "error" ? message_type = "danger" : "success"%>
        <%= content_tag(:div, class: "alert alert-#{message_type}") do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong><%=message_type.capitalize%>!&nbsp;</strong><%=message%>
        <%end%>
      <% end %>

      <%= yield %>
      <!--
      <div class="container">
        <%#= debug(params) if Rails.env.development? %>
      </div>
    -->

  <!-- Font Awesome -->
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  
  </body>
</html>